[theme]
base="dark"  # Keep the dark theme
primaryColor="#1E90FF"  # Bright blue for primary elements
backgroundColor="#121212"  # Very dark gray for the background
secondaryBackgroundColor="#1E1E1E"  # Slightly lighter dark gray for secondary elements
textColor="#FFFFFF"  # White text for contrast
font="sans serif"  # Change to a different font, e.g., "serif", "monospace", or "sans serif"
