[theme]
base="dark"  # Keep the dark theme
primaryColor="#FF5733"  # Bright red for primary elements
backgroundColor="#2C2C2C"  # Dark gray for the background
secondaryBackgroundColor="#3A3A3A"  # Slightly lighter gray for secondary elements
textColor="#FFFFFF"  # White text for contrast
font="sans serif"  # Change to a different font, e.g., "serif", "monospace", or "sans serif"
