[theme]
base="dark"  # Keep the dark theme
primaryColor="#FF0000"  # Bright red for primary elements
secondaryBackgroundColor="#D3D3D3"  # Light gray for sidebar
textColor="#FFFFFF"  # White text for contrast
font="sans serif"  # Change to a different font, e.g., "serif", "monospace", or "sans serif"
